name: "Run black formatter with reviewdog"
description: "🐶 Run black formatter with reviewdog on pull requests to improve code review experience."
author: "Rick Staa"
inputs:
  workdir:
    description: "Working directory relative to the root directory. Defaults to '.'."
    required: false
    default: "."
  format:
    description: |
      If true, black format files and commit are creatable (use other Action).
      Defaults to 'false'.
    required: false
    default: "false"
  fail_on_error:
    description: |
      Exit code when black formatting errors are found [true, false]. Defaults to 'false'.
    required: false
    default: "false"
  # Reviewdog related inputs
  annotate:
    description: "Annotate black changes using reviewdog. Defaults to 'true'."
    required: false
    default: "true"
  github_token:
    description: "The automatically created secret github action token."
    required: true
    default: ${{ github.token }}
  tool_name:
    description: "Tool name to use for reviewdog reporter. Defaults to 'black-format'."
    required: false
    default: "black-format"
  level:
    description: "Report level for reviewdog [info, warning, error]. Defaults to 'error'."
    required: false
    default: "error"
  reporter:
    description: |
      Reporter of reviewdog command [github-pr-check, github-pr-review, github-check].
      Defaults to 'github-pr-check'.
    required: false
    default: "github-pr-check"
  filter_mode:
    description: |
      Filtering mode for the reviewdog command [added, diff_context, file, nofilter].
      Default is added.
    required: false
    default: "added"
  reviewdog_flags:
    description: "Additional reviewdog flags."
    required: false
    default: ""
outputs:
  is_formatted:
    description: "Whether the files were formatted using the black formatter."
runs:
  using: "docker"
  image: "Dockerfile"

# Ref: https://haya14busa.github.io/github-action-brandings/
branding:
  icon: "check"
  color: "blue"
